index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
      route: app.swagger_ui
      permanent: true

api_v1:
  prefix:   /api/v1
  resource: "../src/Controller/API/V1"
  type:     annotation
